// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Appointment
{
    public int Id { get; set; }

    public int PatientId { get; set; }

    public int DoctorId { get; set; }

    public DateOnly? Date { get; set; }

    public string Session { get; set; }

    public string Status { get; set; }

    public DateTime? CheckInTime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Note { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual Examination Examination { get; set; }

    public virtual ICollection<LabTest> LabTests { get; set; } = new List<LabTest>();

    public virtual Patient Patient { get; set; }
}