// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Doctor
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string LicenseNumber { get; set; }

    public string Qualification { get; set; }

    public DateOnly? DateOfLicense { get; set; }

    public DateOnly? LicenseExpiryDate { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Examination> Examinations { get; set; } = new List<Examination>();

    public virtual User User { get; set; }
}