// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Examination
{
    public int Id { get; set; }

    public int? AppointmentId { get; set; }

    public int? DoctorId { get; set; }

    public string ClinicalData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual ICollection<PatientRegimen> PatientRegimen { get; set; } = new List<PatientRegimen>();
}