// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class LabTest
{
    public int Id { get; set; }

    public int? AppointmentId { get; set; }

    public int? TestTypeId { get; set; }

    public DateTime OrderTime { get; set; }

    public string OrderStatus { get; set; }

    public string ResultValue { get; set; }

    public string Unit { get; set; }

    public string ReferenceRange { get; set; }

    public string ResultStatus { get; set; }

    public string Comments { get; set; }

    public DateTime? ResultDate { get; set; }

    public int? LabStaffId { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual User LabStaff { get; set; }

    public virtual TestType TestType { get; set; }
}