// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PatientRegimen
{
    public int Id { get; set; }

    public int? ExaminationId { get; set; }

    public int? RegimenMasterId { get; set; }

    public string CustomNotes { get; set; }

    public virtual Examination Examination { get; set; }

    public virtual TreatmentRegimensMaster RegimenMaster { get; set; }
}