// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Patient
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateOnly Dob { get; set; }

    public string Gender { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string InsuranceNumber { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual User User { get; set; }
}