// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class RegimenDrug
{
    public int Id { get; set; }

    public int? RegimenId { get; set; }

    public int? DrugId { get; set; }

    public string Dose { get; set; }

    public string Frequency { get; set; }

    public virtual ArvDrug Drug { get; set; }

    public virtual TreatmentRegimensMaster Regimen { get; set; }
}