// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TestType
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Unit { get; set; }

    public string ReferenceRange { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<LabTest> LabTests { get; set; } = new List<LabTest>();
}