// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TreatmentRegimensMaster
{
    public int Id { get; set; }

    public string RegimenName { get; set; }

    public string Drugs { get; set; }

    public string Description { get; set; }

    public virtual ICollection<PatientRegimen> PatientRegimen { get; set; } = new List<PatientRegimen>();

    public virtual ICollection<RegimenDrug> RegimenDrugs { get; set; } = new List<RegimenDrug>();
}