// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Role { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }
    public string? FullName { get; set; }


    public virtual Doctor Doctor { get; set; }

    public virtual ICollection<LabTest> LabTests { get; set; } = new List<LabTest>();

    public virtual Patient Patient { get; set; }
}